### ISSUE TITLE
Gestion des dépendances

### ISSUE THREAD

**Issue by yanek** [11rdp/modpack#4]
Comme dit (#2) : 
> [...] Je ne sais pas encore comment gérer les différentes dépendances, je suis juste sûr que je ne veux plus embarquer des assets "étrangers" à l'intérieur même du pack. Le plus simple serait de faire du tout vanilla, ou de ne dépendre que d'addons qui sont utilisés systématiquement (RHS, etc).
> 
> Quoi qu'il en soit la dépendance ACE3 / CBA est inévitable, et je le vis bien.

On a évoqué en vocal avec @Nikkaaa la possibilité  d'un pack optionnel _client side only_ qui pourrait avoir comme dépendances des addons client type JSRS. Il ne serait pas indispensable de l'installer pour jouer, et on n'aurait pas besoin de le mettre sur le serveur.

Ça ne nous dit pas comment faire pour les dépendances qui sont aussi _server side_. Prenons l'exemple de [Taliban Fighters](http://www.armaholic.com/page.php?id=29542), on pourrait en avoir besoin pour le MIST. Mais à ce moment là, il faudrait intégrer l'addon Taliban Fighters à toutes les missions qui utilisent le pack 11RDP, même si on ne combat que des unités RAC, ou autre. 

On peut limiter un max l'utilisation de dépendances, mais dans certains cas j'ai du mal à voir comment. La solution serait de créer autant de mods que de factions, mais ce ne serait pas vraiment une solution non-plus étant donné l'horreur que ce serait à maintenir et intégrer (avec les inter-dépendances entre factions, etc).

**Comment by Nikkaaa** [comment]
De toute manière il est hors de question d'ajouter autre chose que ACE et CBA en dépendance. Je pense qu'on est d'accord la dessus. Grosso modo il reste : 

- Ajouter les dépendances directement dans le pack (je suis moyen chaud sauf si on arrive à libérer les fichiers sources et que ce n'est pas trop lourd).
- Créer autant de mods que de factions comme tu le dis (pour moi ce sera la dernière solution envisageable si on ne trouve rien d'autre).
- Travailler avec des assets vanilla (je ne vois pas comment c'est possible pour coller avec la plupart des maps middle east).
- Trouver un concepteur 3D.

**Comment by yanek** [comment]
Un concepteur 3D ce serait quand même très cool !

Quand j'aurais accès au jeu, je regarderai ce qu'on peut faire avec les assets vanilla. J'essayerai de faire une liste de ce qui nous manque vraiment et de ce qui peut être fait avec de simples textures + config. 

Pour l'intégration directe de certains add-ons au pack, c'est envisageable uniquement dans la mesure où ils sont open source. Mais j'ai l'impression qu'une bonne partie des moddeurs n'a pas pris la peine de spécifier une licence. Et avec tous les simples ports d'Arma 2 c'est toujours un peu galère de retrouver le propriétaire original des modèles 3D. 

Si c'est BIS, ça devrait être sous licence APL, et alors pas de soucis.

**Comment by yanek** [comment]
![arma3_2017-02-11_22-28-41](https://cloud.githubusercontent.com/assets/5952366/22857771/db081a50-f0ab-11e6-93a8-7d3bcb18f6f3.png)

Avec un peu de travail de texture et en admettant que le MIST est plus paramilitaire qu'avant, je pense qu'on peut s'en sortir en tout vanilla.

**Comment by 11RDP-LoupVert** [comment]
Qu'est-ce que vous recherchez exactement comme modèles 3D ?
