### ISSUE TITLE
Réintégration du module AI 

### ISSUE THREAD

**Issue by yanek** [11rdp/modpack#6]
J'ai réintégré le module AI sous forme de prototype (b938b05c92339fb730833593b0cf18b9eeb3d866). Il reste encore beaucoup de choses à faire, mais c'est un module complexe et qui peut rapidement, sans trop qu'on sache pourquoi, influer violemment sur les performances, alors autant tester au fur et à mesure pour éviter de casser quoi que ce soit.

### Il faudrait confirmer le fonctionnement de : 
- [x] L'IA ennemie réagit correctement aux tirs proches sur serveur dédié.
- [x] Essayer avec et sans silencieux
- [x] Essayer avec des munitions subsoniques
- [x] Essayer avec des conditions météo différentes

### Reste à faire : 
- ~~Une meilleure gestion des fumigènes par les IA~~ (752c30c6991fe655ba65f0b564dfa7369a3d4117)
- ~~Une gestion des flares~~ (752c30c6991fe655ba65f0b564dfa7369a3d4117)
- ~~Différents tweaks pour rendre les calculs plus réalistes, précis, équilibrés~~ (4eac8bf9909f5b5299ce2ecf5b707a4dc06599f2, afd9d5823af34d8fe1a9bfa7c8f41be6cafd5948)
- ~~L'ajout / le retrait automatique des JVN en fonction de la luminosité~~ (6c8aba31b3877018792ea8e4406f261154a6ba41)

Si vous avez des requêtes ou des idées de choses à ajouter au module AI, n'hésitez pas à faire un tour dans la [boite à idées](https://github.com/11rdp/modpack/issues/1).

**Comment by yanek** [comment]
Je veux intégrer le calibre de l'arme en tant que paramètre dans le calcul du bruit (et notamment de la portée du bruit) des coups de feu, de manière à rendre encore un peu plus précis la détection par les IA basée sur le son.

Seulement ma connaissance en arme à feu est trop limitée et je veux pas improviser des valeurs aléatoires. Alors si vous avez de la documentation ou des connaissances sur le sujet, je suis preneur !

**Comment by Sociohunter** [comment]
https://ereverra.files.wordpress.com/2012/08/ere_acoustique_champstir.pdf
En fait plus que du calibre c'est l'arme et le type de munition. Après au final ça varie pas des masses en terme de puissance audio, c'est souvent autour de 125dB. 
Pour la portée, le souci c'est que ça dépend de la fréquence de l'onde, du terrain(type), du relief, des conditions atmosphériques... J'avoue que je sais pas trop.
